/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MarkerType = "NoAction" | "YesAction" | "Selection";

export interface MarkerComponent {
  markerType: MarkerType;
  iconId: string;
  [k: string]: unknown;
}
