/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PieceComponent {
  identifier: PieceIdentifier;
  [k: string]: unknown;
}
export interface PieceIdentifier {
  pieceTypeId: string;
  shortName: string;
  iconId: string;
  /**
   * The numerical ID of the Player that owns this piece.
   */
  ownerId: number;
  /**
   * A number in range [0, 360) indicating the forwards-direction of this piece. (With 0 being 'North')
   */
  forwardBasis: number;
  [k: string]: unknown;
}
