/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BoardUpdateSubscribe {
  /**
   * the sessionId of the game instance to register with
   */
  sessionId: string;
  /**
   * Index of the player (>= 0) whose perspective to show
   */
  perspective: number;
  [k: string]: unknown;
}
