/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ChatMessage {
  /**
   * userName of the message sender
   */
  userName: string;
  /**
   * the actual text content of the message
   */
  message: string;
  /**
   * the time of receipt of the message in milliseconds since the Unix epoch
   */
  timestamp: number;
  [k: string]: unknown;
}
