/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GameClicked {
  sessionId: string;
  /**
   * tileId of the clicked tile
   */
  clickedTile: string;
  [k: string]: unknown;
}
