/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OfferPieceSelection {
  /**
   * Title for the Selection Window
   */
  title: string;
  pieces: {
    pieceTypeId?: string;
    iconId?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
