import type { Metadata } from "next";
import { Play } from "next/font/google";
import "./globals.css";

const playFont = Play({ weight: "400", style: "normal", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={playFont.className}>{children}</body>
        </html>
    );
}

